#!/usr/bin/env bash
# Generate the shipped-script integrity manifest — the artifact that lets an adopting repo
# tell an upgraded shipped script from a locally edited one, offline and with no network.
#
#   scripts/build-manifest.sh            write both copies of the manifest
#   scripts/build-manifest.sh --stdout   write to stdout (used by the drift guard)
#
# Repo-local tooling, like scripts/build-dist.sh: it runs FROM the harness's source of truth
# and is never shipped. An adopter receives the OUTPUT, not this script.
#
# TWO copies are written, and they are the same two the rest of this repo already maintains:
#
#   harness/templates/scripts/MANIFEST.sha256   the shipped artifact, installed by amh-init.sh
#   scripts/MANIFEST.sha256                     this repo's own instance of it
#
# The second is not redundant. This repository is the harness's reference instance, so its
# ladder runs the shipped integrity rung against itself; without a manifest here that rung
# would print `skip` forever in the one tree where it is easiest to keep honest — a guard
# tested only in someone else's repo. scripts/guards/copy-drift.sh holds the two byte-identical
# (it compares every file under harness/templates/scripts/, not only the *.sh ones), and
# scripts/guards/manifest-drift.sh holds this generator's output against what is committed.
#
# Hashes are taken over the TEMPLATE files, which are the originals; the copies under scripts/
# are byte-identical by copy-drift.sh, so hashing either gives the same answer.

set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." || exit 1

SRC=harness/templates/scripts
NAME=MANIFEST.sha256
VERSION=$(tr -d '[:space:]' <harness/VERSION)

# The tool is resolved ONCE, here, at the top level — never inside sha256_of. `exit` inside a
# command substitution kills the substitution's subshell and nothing else, so a version of this
# check that lived in the function printed its diagnostic five times and then wrote a manifest
# of empty hashes over both copies, reporting success. A release-artifact generator that fails
# open is worse than one that will not run: the artifact it produced would have been a file
# that verifies nothing, published under a version number.
if command -v sha256sum >/dev/null 2>&1; then
	HASHER=sha256sum
elif command -v shasum >/dev/null 2>&1; then
	HASHER=shasum
else
	printf 'build-manifest: no sha256sum or shasum on PATH — cannot generate the manifest\n' >&2
	exit 1
fi

# Read from STDIN rather than passing the path: it collapses the two tools' output formats
# and keeps every filename out of a tool's argument parsing.
sha256_of() { # <file>
	case $HASHER in
	sha256sum) sha256sum <"$1" ;;
	shasum) shasum -a 256 <"$1" ;;
	esac | sed 's/[^0-9a-f].*//'
}

emit() {
	# The paths are written as the ADOPTER sees them — `scripts/<name>`, relative to their
	# repo root — because that is the tree the manifest is verified against. It is also what
	# makes `sha256sum -c scripts/MANIFEST.sha256` work by hand from a repo root, which is
	# the escape hatch for anyone who does not trust the rung.
	printf '# AMH %s — integrity manifest for the shipped scripts.\n' "$VERSION"
	printf '# GENERATED by scripts/build-manifest.sh in the harness repo. Do not hand-edit:\n'
	printf '# a ladder rung compares your scripts/ against these hashes, and a guard in the\n'
	printf '# harness repo rebuilds this file and diffs it.\n'
	printf '#\n'
	printf '# Editing a shipped script is what this catches. The change belongs in amh.conf,\n'
	printf '# in a guard under scripts/guards/, or in scripts/verify.sh. Check by hand with:\n'
	printf '#   sha256sum -c scripts/%s\n' "$NAME"
	local f
	for f in "$SRC"/*.sh; do
		printf '%s  scripts/%s\n' "$(sha256_of "$f")" "$(basename -- "$f")"
	done
}

if [ "${1:-}" = "--stdout" ]; then
	emit
	exit 0
fi

emit >"$SRC/$NAME"
cp -- "$SRC/$NAME" "scripts/$NAME"
printf 'wrote %s and scripts/%s (%s script(s))\n' \
	"$SRC/$NAME" "$NAME" "$(find "$SRC" -name '*.sh' | wc -l | tr -d ' ')"
